run:
  go: 1.22
  concurrency: 4
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - exportloopref
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
