name: destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which AWS resources environment would you like to destroy?
        options:
          - dev
          - prod

jobs:
  destroy:
    name: destroy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Terraform destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export TF_WORKSPACE=${{ github.event.inputs.environment }}
          cd infra/
          docker compose run --rm terraform -chdir=deploy init
          docker compose run --rm terraform -chdir=deploy destroy -auto-approve
